// Every word the interface says, in both languages. Keys must match exactly;
// scripts/copy_audit.mjs checks that they do.
const fmt = (v) => (v == null ? "—" : (+v).toFixed(2));

export const COPY = {
  en: {
    newChat: "New task", newFolder: "Folder", archived: "Archived", chats: "Tasks",
    emptySide: "Nothing yet.", settings: "Settings", chooseWs: "Choose a workspace",
    rename: "Rename", archive: "Archive", unarchive: "Restore", del: "Delete",
    moveTo: "Move to", noFolder: "Out of folder", confirmDelete: "Delete this task?",
    deleteFolder: "Delete folder", folderName: "Folder name", working: "Running",

    promptPlaceholder: "Describe a task, or an app to build",
    attachFile: "Upload a file", attachText: "Paste text", material: "Material",
    skillAuto: "Skill: auto", skillNone: "No skill",
    appMode: "App", appModeOn: "Builds an app", appModeOff: "Jev decides when to build an app",
    sendHint: "↵ send · ⇧↵ new line", willQueue: "Busy — this will queue",
    queuedN: (n) => `${n} waiting`, waiting: "waiting", stopped: "Stopped.",
    needPrompt: "Nothing to send.", needKey: "Add a key first.",
    needWorkspace: "Choose a workspace before starting a task.",

    panelWs: "Workspace", panelKeys: "Keys", panelModels: "Models", panelJev: "Jev",
    none: "none", fromEnv: ".env", ready: "ready", missing: "missing",
    nKeys: (n) => `${n} key${n === 1 ? "" : "s"}`, nModels: (n) => `${n} model${n === 1 ? "" : "s"}`,

    you: "You", jevia: "JEVia", jevOnly: "Jev only", via: "via",
    copy: "Copy", copied: "Copied", again: "Edit & resend", savedTo: "Saved to",
    details: "Ledger", openApp: "Open app", outputs: "Outputs", download: "Download",
    cache: "Cache hits", wall: "Time", unsure: "unsure",
    gistYes: "Yes", gistNo: "No", gistIs: "Reads", gistUnsure: "Unsure",
    gistCount: (n, u) => `${n} judgement${n === 1 ? "" : "s"}${u ? `, ${u} unsure` : ""} · one Jev call`,
    judged: "What Jev decided", showAll: "Every judgement in full",
    composed: "Composed by Jev", layout: "Layout", layouts: { single: "one column", split: "main + side", grid: "grid" },
    components: {
      hero: "Title", stats: "Numbers", form: "Form", table: "Table", cards: "Cards", chart: "Chart",
      filter: "Search", checklist: "Checklist", timeline: "Timeline", tabs: "Tabs", steps: "Progress",
      text: "Text", list: "List", callout: "Notice",
    },
    sources: "Sources", web: "web",
    stSearch: "search", stPicked: "picked", stFetch: "read", stFilter: "kept",
    picked: (a, b) => `${a} of ${b}`, keptOf: (a, b, e) => `${a} of ${b} sections · enough ${e}`,
    strategies: {
      declared: "declared", one_choice: "classify", one_score: "rate", one_noul: "yes/no",
      generation_only: "write", llm_only: "direct", app: "app",
    },
    ops: { yes: "yes", no: "no", is: "=", at_least: "≥", below: "<" },
    skips: { decisions_only: "decisions only", jev_only: "decisions only", gate: "gated" },
    steps_: {
      assess: (d) => (d.app ? "an app" : d.needs_research ? "needs looking up" : "material is enough")
        + (d.multi_step ? " · several stages" : "")
        + (d.skill ? ` · ${d.skill}` : ""),
      plan_free: () => "plan recognised locally",
      plan_compiled: (d) => `${d.decisions} decisions extracted, plan cached`,
      research: (d) => `${d.hits} results → ${d.kept}/${d.sections} sections, ${d.sources} sources`,
      route: (d) => `${d.steps} steps across ${d.models} model(s)${d.skipped ? `, ${d.skipped} skipped` : ""}`,
      jev_batch: (d) => `${d.decisions} decisions in one call${d.sized_model ? ", model sized" : ""}${d.uncertain ? `, ${d.uncertain} unsure` : ""}`,
      gate: (d) => `skipped — ${d.condition_text || d.condition}`,
      gate_ignored: () => "gate ignored, research found the answer",
      jev_only: () => "nothing to write",
      model: (d) => `${d.model}${d.rounded_up ? " (moved up)" : ""}`,
      model_pinned: (d) => `${d.model}, pinned`, model_forced: (d) => `${d.model}`,
      generate: (d) => `${d.model} · ${d.output_tokens} tokens`,
      subtask: (d) => `${d.title} — ${d.model}`,
      tool_gate: (d) => `${d.allowed || 0} of ${d.asked || 0} tool calls allowed`,
      assemble: (d) => `rewritten as one piece on ${d.model}`,
      assemble_free: (d) => `${d.sections} sections joined`,
      escalate: (d) => `${d.count} sent to ${d.model}`,
      guard: () => "output checked", retry: () => "missed the brief — one more try",
      compose: (d) => (d.kind === "code" ? "needs code of its own" : `${(d.components || []).length} components, ${d.layout}`),
      layout: (d) => `${(d.side || []).length} in the side panel`,
      app_fill: (d) => `words by ${d.model}`,
      failover: (d) => `${d.from} unavailable (${d.reason}) → ${d.to}`,
      app_write: (d) => `written by ${d.model} · ${Math.max(1, Math.round((d.chars || 0) / 1024))} KB`,
    },

    // workspace
    wsTitle: "Choose a workspace", wsNote: "Every task, file and app is saved in this folder.",
    use: "Use this folder", newHere: "New folder here", newHereName: "Name",
    create: "Create", cancel: "Cancel", typePath: "Type a path…", close: "Close", enter: "open",
    wsEmpty: "No folders here.", wsMissing: "This folder does not exist yet.",
    wsReady: (n) => `Ready · ${n} folder${n === 1 ? "" : "s"} inside`, wsReadonly: "This folder is not writable.",
    created: (n) => `Created “${n}”.`, wsSet: "Workspace set to",

    // onboarding
    welcome: "Set up JEVia", welcomeKey: "Paste an OpenRouter key to start. It powers Jev and the models; other providers can be added later.",
    welcomeGet: "Get a key", otherVendors: "Use another provider", start: "Continue", later: "Later",

    // preferences
    prefs: "Settings", saved: "Saved",
    tabTools: "Tools", toolsNote: "What a run may do, and the tools it can reach.",
    tabKeys: "Keys", tabModels: "Models", tabSkills: "Skills", tabLoops: "Loops", tabMemory: "Memory", tabBehaviour: "Behaviour",
    keysNote: "Add a key for every provider you use. Keys stay in this browser and are sent only to that provider.",
    jevNeedsKey: "Jev runs through OpenRouter or TypeSafe. Add one of those keys, or JEVia cannot decide anything.",
    addKey: "Add a key", keyPlaceholder: "Paste the key", baseUrl: "Base URL", label: "Name",
    getKey: "Get a key", addAndTest: "Add & test", testing: "Testing…", remove: "Remove",
    keyOk: (n) => `Connected · ${n} models`, keyAdded: "Key added", keyRemoved: "Key removed",
    jevHere: "Jev", chatHere: "Models", envKey: "From .env", noKeys: "No keys yet.",
    modelsNote: "Every task runs on the cheapest model that can do it. Add a few of different strength.",
    yourModels: "In use", addModels: "Add models", browseWith: "Browse with",
    search: "Search", tabAll: "All", tabFree: "Free", tabCheap: "Under $1", tabAdded: "Added",
    add: "Add", added: "Added", free: "free", noPrice: "no price",
    noModels: "No models yet — add at least one.", needChatKey: "Add a key that can run models first.",
    loading: "Loading…", tierWhy: ["", "copying and reformatting", "everyday writing", "reasoning and code", "the hardest work"],
    modelAdded: "Model added", modelRemoved: "Model removed",
    skillsNote: "A skill is a set of house instructions. JEVia picks one per task, or you can choose it in the composer.",
    newSkill: "New skill", install: "Install", installFrom: "Install from a link (GitHub or raw .md)",
    builtIn: "built-in", yours: "workspace", edit: "Edit", back: "Back", save: "Save",
    skillSaved: "Skill saved", skillDeleted: "Skill removed", skillInstalled: "Skill installed",
    skillsNeedWs: "Skills you add or edit are stored in the workspace — choose one first.",
    loopsNote: "A schedule runs a task on a timer. Give it a goal and it becomes a loop: it keeps going until Jev judges the goal met.",
    loopName: "Name", loopPrompt: "What should it do?", loopEvery: "Every", loopGoal: "Until (optional goal)",
    loopGoalHint: "e.g. the draft is under 200 words and has a clear call to action",
    loopMax: "At most", rounds: "rounds", startNow: "Start now", createLoop: "Create",
    loopKeyWarn: "The key is stored in the workspace (readable only by you) so it can run with the browser closed.",
    noLoops: "Nothing scheduled.", loopsNeedWs: "Choose a workspace first — a schedule has to be stored somewhere.",
    runNow: "Run now", pause: "Pause", resume: "Resume", lastRun: "last run", never: "never",
    status: { active: "active", paused: "paused", done: "done", failed: "failed" },
    goalMet: "goal met", runLimit: "run limit", loopTag: "loop", goal: "Goal", loopCreated: "Created", minutes: "min", hours: "h", day: "day",
    everyN: (m) => (m % 1440 === 0 ? `every ${m / 1440} day` : m % 60 === 0 ? `every ${m / 60} h` : `every ${m} min`),
    memoryNote: "What JEVia has learned about you. It is used to tailor answers and can be deleted at any time.",
    memoryOn: "Remember what I tell you about myself", rememberThis: "Add something to remember",
    forget: "Forget", forgetAll: "Forget everything", noFacts: "Nothing remembered yet.", memoryNeedsWs: "Memory lives in the workspace — choose one first.",
    stated: "you said", typed: "you added",
    behaviourNote: "How cautious and how thrifty JEVia should be.",
    stance: [
      { id: "thrifty", t: "Thrifty", d: "fewer model calls" },
      { id: "balanced", t: "Balanced", d: "default" },
      { id: "careful", t: "Careful", d: "double-check close calls" },
    ],
    optResearch: "Web research", optResearchD: "Search and read the web when a task needs facts.",
    optEscalate: "Settle close calls", optEscalateD: "When Jev is unsure, a model looks again.",
    optGuard: "Check every answer", optGuardD: "Jev checks the answer against the task; a miss gets one more try.",
    optApps: "Build apps", optApps_D: "When you ask for a tool, form or dashboard, Jev composes a working one.",
    optTools: "Workspace tools", optToolsD: "Let workers read and write files in the workspace.",
    // slash menu, dropdowns, apps, canvas
    expand: "Show all", collapse: "Show less", latest: "Latest",
    thinking: "Jev is reading the task…", planning: (x) => `Jev: ${x} — planning the steps…`, researching: "Searching and reading…",
    jevLevel: (n) => `Jev rated it level ${n} of 4`, rejected: (x) => `cheaper ${x} not up to it`,
    switched: (a, b) => `${a} unavailable, used ${b}`,
    workers: "Workers", worker: "Worker", bespoke: "custom", doc: "Document", brief: "Its brief",
    status_: { pending: "waiting", running: "working", done: "done", skipped: "skipped", failed: "failed" },
    revisedN: (n) => `revised ${n}×`, revisedNote: "Rewrote its part.",
    talkTo: "Tell this worker what to change — it rewrites its part", answerNotSynced: "The combined answer was rewritten as one piece, so it still shows the earlier version of this part.",
    assembled: "Assembled", filling: (m) => `Parts in place · words by ${m}`,
    log: {
      tool: (e) => `${e.ok ? "used" : "refused"} ${e.name}`,
      search: (e) => `Searched “${e.q}”`, read: (e) => `Opened ${e.n} page${e.n === 1 ? "" : "s"}`,
      kept: (e) => `Kept ${e.n} passage${e.n === 1 ? "" : "s"}`, write: (e) => `Writing on ${e.model}`,
      error: (e) => e.message || "Failed",
      failover: (e) => `${e.from} unavailable (${e.reason}); switched to ${e.to}`,
    },
    slashTitle: "Skills & commands", slashHint: "↑↓ choose · ↵ use · esc close", slashEmpty: "Nothing matches",
    skillLabel: "Skill", skillAutoShort: "Auto", cmdApp: "Build it as an app", cmdAppOff: "Let Jev decide about apps",
    cmdNone: "Use no skill", cmdAuto: "Let Jev pick the skill",
    skillNames: {
      "research-brief": "Research brief", "code-review": "Code review", "support-reply": "Customer reply",
      summarise: "Summarise", "compare-options": "Compare options", "data-extraction": "Extraction",
      "writing-clear": "Plain writing", translate: "Translate",
    },
    skillDescs: {
      "research-brief": "Writing a short, sourced account of something you had to look up.",
      "code-review": "Judging a diff, a pull request, or a proposed change.",
      "support-reply": "Answering a customer, user or member of the public.",
      summarise: "Compressing long material into what someone needs to act on.",
      "compare-options": "Weighing alternatives and recommending one.",
      "data-extraction": "Pulling specific values out of material into a fixed shape.",
      "writing-clear": "Producing prose that a busy reader will actually finish.",
      translate: "Moving text between languages while keeping what matters.",
    },
    forging: (kb, model) => `Writing the app · ${kb} KB${model ? " · " + model : ""}`,
    kindCode: "own code", forgeNote: "Standard parts cannot build this — a model writes it whole.",
    run: "Run", webSources: "Web pages", openSite: "Open", sectionsKept: (n) => `${n} passage${n === 1 ? "" : "s"} used`,
    canvasEmpty: "Apps, documents and the web pages a task read will appear here.",
    heroDisplay: "Judge. Write. Build.",
    advanced: "Advanced", thAbstain: "Unsure below", thLow: "Yes/no low", thHigh: "Yes/no high", jevModel: "Jev model",
    interrupted: "Interrupted: the page was closed before this finished. Nothing new was started afterwards.",
    uploadSkill: "Upload",
    plainHttpKey: "That address is plain http: your key will cross the network unencrypted.",
    skillsAdded: (n, ignored) => `${n} skill${n === 1 ? "" : "s"} added${ignored ? `, ${ignored} file${ignored === 1 ? "" : "s"} ignored` : ""}`,
    stoppedListening: "Stopped listening. The run may still finish on the server, and its last request may still be billed.",
    dp: {
      qualityTitle: "Spending",
      qualityNote: "Jev sizes every step the same way; this decides which side of that size the model comes from.",
      qualities: { thrift: "Cheapest that fits", best: "Best available" },
      qualityNotes: {
        thrift: "The cheapest model that clears each step. The usual bargain.",
        best: "The strongest model you have configured, on every step that needs writing.",
      },
      mcpTitle: "Tools from elsewhere (MCP)",
      mcpNote: "An MCP server is a program that offers tools. It runs on this machine as you, so it is configured here and nowhere else — never by a model.",
      mcpName: "Name", mcpCommand: "Command", mcpAdd: "Add server",
      mcpWarning: "Only add servers you trust: the command runs as you.",
      mcpReady: (n) => `${n} tool${n === 1 ? "" : "s"}`, mcpFailed: "did not start",
      mcpOff: "off", mcpEnable: "Enable", mcpDisable: "Disable",
      mcpEmpty: "No MCP servers yet.",
      toolsTitle: "Tools", toolsNote: "What a run may do on your machine. Every change is judged before it runs, and stays inside the workspace.",
      toolSets: { read: "Look only", write: "Read and write", full: "Also run commands" },
      toolSetNotes: {
        read: "Read files, search, fetch pages. Changes nothing.",
        write: "Also write and edit files inside the workspace.",
        full: "Also run shell commands and code. Needs JEVIA_ENABLE_SHELL=1.",
      },
      planModePref: "Show the plan first",
      planModeNote: "Before any work, show what it intends to do and wait. Say what to change and it replans.",
      approvePref: "Ask before each change",
      approveNote: "Every write, edit or command waits for you, on top of the safety judgement.",
      loopPref: "Let the model use tools in steps",
      loopNote: "It can read a result and decide the next move. Off makes every answer a single request.",
      maxSteps: "Steps per turn", maxStepsNote: "How many times one answer may look before it writes.",
      ofOpen: (n) => `${n} waiting`,
      questionAsked: "The run has a question", approvalNeeded: "Approve this change?",
      approvalNote: "It changes something outside this conversation.",
      planReady: "The plan, before any work starts", planChange: "Say what to change instead…",
      answerHere: "Your answer…", send: "Send",
      planTitle: "Plan", planWaiting: "waiting for you", planApproved: "approved by you",
      planChanged: "changed on your feedback",
      stepsTitle: "Steps and tools",
      stepsLine: (n, t) => `${n} step${n === 1 ? "" : "s"} · ${t} tool call${t === 1 ? "" : "s"}`,
      stepN: (n) => `Step ${n}`,
      calledTools: (n) => `called ${n} tool${n === 1 ? "" : "s"}`,
      waitingModel: "waiting for the model…", answered: "answered",
      toolsFailed: (n) => `${n} refused or failed`,
      compacted: (n) => `context summarised ×${n}`,
      compactedLine: (a, b, n) => `Older exchanges summarised: ${a} → ${b} tokens, ${n} message${n === 1 ? "" : "s"} replaced`,
      toolStates: { running: "running…", ok: "ok", failed: "failed", refused: "refused" },
      refusals: {
        unknown_tool: "no such tool in this run", malformed_arguments: "arguments were not valid JSON",
        gate_refused: "refused by the gate", user_refused: "you refused it",
        gate_not_asked: "not part of what you asked for", gate_unsafe: "judged unsafe",
        gate_unavailable: "the gate could not be reached",
        already_refused: "the same call, already refused",
        no_gate: "could not be checked", no_tools: "tools are off for this run",
      },
      showEarlier: (n) => `Show ${n} earlier batch${n === 1 ? "" : "es"}`,
      showAllQuestions: (n) => `Show all ${n} questions`,
      qnames: {
        __needs_research__: "Needs web research", __multi_step__: "Several parts", __wants_app__: "Wants an app",
        __skill__: "Which skill", __enough__: "Evidence enough", __capability__: "Capability needed",
        __independent__: "Steps independent", __assembly__: "Rewrite as one piece",
        on_task: "Answer on task", refused: "Answer refuses", web: "Needs fresh facts",
      },
      actions: {
        "search the web": "search the web",
        "use the material given": "use the material given",
        "compile a plan with steps": "compile a plan with steps",
        "no forced split": "no forced split",
        "build an app": "build an app",
        "answer in text": "answer in text",
        "no skill": "no skill",
        "skip generation": "skip generation",
        "generate anyway": "generate anyway",
        "no generation call": "no generation call",
        "run": "run",
        "block": "block",
        "keep the partial text; no automatic retry": "keep the partial text; no automatic retry",
      },
      viewDecisions: "View decisions", decisionSummary: "Decision summary", decisions: "Decisions",
      countsLine: (q, j, l) => `${q} judgement${q === 1 ? "" : "s"} · ${j} Jev call${j === 1 ? "" : "s"} · ${l} LLM call${l === 1 ? "" : "s"}`,
      oneCall: (n) => `1 call · ${n} question${n === 1 ? "" : "s"}`,
      stages: {
        running: "Running", assessing: "Assessing task", planning: "Planning", searching: "Searching the web",
        reading: "Reading sources", choosingSources: "Choosing sources", classifying: "Classifying sources",
        checkingEvidence: "Checking evidence", routing: "Routing steps", judging: "Judging",
        writing: "Writing", assembling: "Assembling", checkingAnswer: "Checking the answer",
        reviewing: "Reviewing uncertain answers", runningTools: "Running tools", buildingApp: "Building the app",
        revising: "Revising",
      },
      status: {
        running: "Running", completed: "Completed", needs_review: "Needs review", cancelled: "Cancelled",
        cancel_requested: "Cancel requested", failed: "Failed", partial: "Partial result",
        interrupted: "Interrupted",
      },
      actors: { jev: "Jev", policy: "Policy", llm: "LLM", tool: "Tool" },
      purposes: {
        assess: "Assessing task", triage: "Choosing sources", filter: "Classifying sources",
        sufficiency: "Checking evidence", route: "Routing steps", decide: "Judging", compose: "Composing the app",
        layout: "Laying out the app", guard: "Checking the answer", gate: "Checking tool actions",
        revise_assess: "Assessing the revision", loop: "Checking the goal",
      },
      reasons: {
        no_qualified_model: "No qualified model", jev_failed: "Jev request failed",
        low_confidence: "Low confidence", evidence_unknown: "Evidence unknown",
        component_schema: "Component check failed",
      },
      sources_: { live: "Live", recorded: "Recorded run", demo: "Demo replay" },
      types: { noul: "Noul", choice: "Choice", score: "Score" },
      groups: { kept: "Kept", review: "Needs review", excluded: "Excluded", not_assessed: "Not assessed" },
      sufficiency: {
        sufficient: "Sufficient", insufficient: "Insufficient", unknown: "Unknown",
        not_rechecked: "Not rechecked for this step", not_checked: "Not checked",
      },
      stops: {
        sufficient: "Stopped: evidence sufficient", budget_exhausted: "Stopped: search budget used",
        no_new_sources: "Stopped: no new sources", error: "Stopped: error", cancelled: "Stopped: cancelled",
      },
      costSources: { provider_reported: "Provider reported", price_table_estimated: "Price table estimate", unknown: "Unknown" },
      modes: { written: "written", partial: "partial", joined: "joined", rewritten: "rewritten", revised: "revised", stale: "stale" },
      tech: {
        question: "Question id", batch: "Batch", attempt: "Attempt", call: "Call", costSource: "Cost source",
        cost: "Cost", operation: "Operation", stage: "Stage", evidenceSet: "Evidence set", limit: "Budget (chars)",
      },
      rules: {
        "assess.research_at_or_above": (i, a) => `Web research: P(yes) ${fmt(i.probability_yes)} vs ${fmt(i.threshold)} → ${a}`,
        "assess.multi_step_at_or_above": (i, a) => `Several parts: P(yes) ${fmt(i.probability_yes)} vs ${fmt(i.threshold)} → ${a}`,
        "assess.app_at_or_above": (i, a) => `App: P(yes) ${fmt(i.probability_yes)} vs ${fmt(i.threshold)} → ${a}`,
        "assess.skill_confidence_at_or_above": (i, a) => `Skill: confidence ${fmt(i.confidence)} vs ${fmt(i.threshold)} → ${a}`,
        "triage.keep_above": (i, a) => `Open results with P(yes) ≥ ${fmt(i.threshold)}, at most ${i.top_k} → ${a}`,
        "triage.keep_best_when_none_pass": (i, a) => `None reached ${fmt(i.threshold)}; the best one is opened → ${a}`,
        "triage.fallback_rank_order": (i, a) => `Jev did not answer; engine order is used → ${a}`,
        "capability.round_to_nearest": (i) => `Raw score ${fmt(i.raw)} rounded to the nearest level${i.adopted != null ? ` (${i.adopted})` : ""}`,
        "capability.round_up_below_certainty": () => "Raised one level: confidence was below the round-up threshold",
        "capability.round_up_relaxed": () => "The raised level had no model; Jev's own level was used instead",
        "capability.no_answer_cheapest": () => "No capability answer: the cheapest model is used",
        "role.min_capability": () => "Raised to the role's minimum level",
        "capability.level0_no_generation": () => "Level 0: the decisions are the answer, so no generation call",
        "capability.level0_without_decisions_generates": () => "Level 0 but nothing to answer with: generate on the cheapest model",
        "gate.skip_generation_when": (i, a) => `The plan's gate fired → ${a}`,
        "gate.ignored_when_research_found_evidence": (i, a) => `Gate ignored: research found evidence → ${a}`,
        "failover.before_output": (i, a) => `${i.from} failed before writing (${i.reason}) → ${a}`,
        "failover.not_after_output": (i, a) => `Failed after ${i.streamed_chars} characters → ${a}`,
        "review.escalate_low_confidence": (i, a) => `Low confidence → ${a}`,
        "guard.retry_once_when_off_task": (i, a) => `The check found the answer off task → ${a}`,
        "tools.gate_allow_at_or_above": (i, a) => `${i.tool}: P(yes) ${fmt(i.probability_yes)} vs ${fmt(i.threshold)} → ${a}`,
        "routing.jev_failed_cheapest": () => "Routing was not answered: the cheapest model is used",
        "r01.contradiction_raises_level": () => "Contradicting material: raised one level (experimental)",
        "r01.incomplete_evidence_fetches_more": () => "Material incomplete: this step looks things up first (experimental)",
        "plan.pinned_model": () => "The plan pins a model",
      },
      sum: { assess: "Assessed task", evidence: "Classified sources", routing: "Routed steps", decisions: "Judged" },
      selectedN: (n) => `${n} selected by policy`,
      groupsCount: (c) => `Kept ${c.kept || 0} · Needs review ${c.review || 0} · Excluded ${c.excluded || 0} · Not assessed ${c.not_assessed || 0}`,
      discoveredLine: (c) => `Discovered ${c.discovered || 0} · submitted ${c.submitted || 0} · evaluated ${c.validly_evaluated || 0}`,
      round: (n) => `Round ${n}`, moreItems: (n) => `${n} more not listed`,
      visibleRange: (v) => `judged ${v[1]} of ${v[2]} chars`,
      checkedDelivered: (n, c) => `Checked the ${n} section${n === 1 ? "" : "s"} the writer receives (${c} chars)`,
      deliveryCheck: "This step receives a subset of the checked evidence",
      excludedNote: "Excluded means not sent to the writer. Nothing was deleted.",
      material: "Material", stepMaterial: "Material for a step",
      routingTitle: "Routing", assessedByJev: "Assessed by Jev", selectedByPolicy: "Selected by policy",
      noQualified: "No qualified model", belowLevel: "Below required level", requiredLevel: "Required level",
      rawScore: "Raw score", adopted: "Adopted", onScale: (a, b) => `on ${a}–${b}`, role: "Role", fromPlan: "from the plan",
      candidates: "Candidates", byCost: "Eligible", priceUnknown: "Price unknown", freeAtRate: "Free at configured rate",
      costBasis: "Ranked by configured cost (input + 3× output price). Not a promise of the lowest total price.",
      bestAvailable: (n) => `Best available: level ${n}`, downgraded: "Downgraded with permission",
      routeWhy: (need, n) => `Required level ${need}; ${n} eligible candidate${n === 1 ? "" : "s"}; ranked by configured cost`,
      addModel: "Add a model", allowDowngrade: "Allow downgrade",
      generationTitle: "Generation", generationSkipped: "Generation skipped", zeroLLM: "0 LLM calls",
      noGenCallStep: "No generation call for this step", scopeRun: "Whole answer", scopeStep: (t) => `Step: ${t}`,
      needsReview: "Needs review", laterAttempt: (a) => `Later, ${a}`,
      costsTitle: "Calls and cost", judgements: "Judgements", jevCalls: "Jev calls", llmCalls: "LLM calls",
      knownCost: "Known cost", unknownCost: "Unknown cost (requests)",
      outputsTitle: "Output versions", wholeAnswer: "Whole answer", dependsOn: "from", needsSync: "Needs sync",
      needsSyncNote: "A part changed after the whole was rewritten from it.", syncNow: "Sync now", synced: "Synced",
      componentsTitle: "App components", componentSlots: "Component slots", componentReady: "Rendered",
      componentFailed: "Component check failed", exampleData: "Example data", codeKind: "Written as code of its own",
      pYes: "P(yes)", pYesShort: "P(yes)", pOf: "p", confidence: "Confidence", threshold: "Threshold",
      distribution: "Distribution", total: "Total", viewAll: "View all", unassigned: "Not classified",
      groupView: "Group by category", listView: "List", unavailable: "Unavailable", missing: "Missing answer",
      failed: "Failed", settled: "Settled", waitingJev: "Waiting for Jev…",
      whyThis: "Why this result", technical: "Technical details",
      cancelRequested: "Cancel requested", mayBill: "The last request may still be billed",
      traceUnavailable: "Detailed trace unavailable", recordGap: (g) => `Record gap: events ${g.map(([a, b]) => (a === b ? a : `${a}–${b}`)).join(", ")} missing`,
      loadFull: "Load full record", exportRecord: "Export record",
      demoNote: "Built from test fixtures. No model was called, and the values are not measurements.",
      demoTitle: "Demo replay", demoPick: "Choose a scenario", replay: "Replay", speed: "Speed",
      motion: "Motion", motionNote: "How state changes are shown. Results and calls are the same in every setting.",
      motionModes: { system: "Follow system", reduced: "Reduced", off: "Off" },
      downgradePref: "Allow labelled downgrade",
      downgradeNote: "When no model reaches a step's level, run it on the strongest one and label it. Off: the step waits for review.",
      extraRouting: "Extra routing dimensions (experimental)",
      extraRoutingNote: "Also ask whether material is complete or contradictory. Off by default until shown to help.",
      loopIteration: (n, m) => `Iteration ${n}${m ? ` of ${m}` : ""}`, goalMet: "Goal met", limitReached: "Limit reached",
      checkedByCode: "checked by code", checkedByJev: "checked by Jev",
    },
  },

  zh: {
    newChat: "新任务", newFolder: "文件夹", archived: "归档", chats: "任务",
    emptySide: "还没有任务。", settings: "设置", chooseWs: "选择工作区",
    rename: "重命名", archive: "归档", unarchive: "取消归档", del: "删除",
    moveTo: "移到", noFolder: "移出文件夹", confirmDelete: "删除这个任务？",
    deleteFolder: "删除文件夹", folderName: "文件夹名称", working: "进行中",

    promptPlaceholder: "说一个任务，或者要做的应用",
    attachFile: "上传文件", attachText: "粘贴文本", material: "材料",
    skillAuto: "技能：自动", skillNone: "不用技能",
    appMode: "应用", appModeOn: "直接做成应用", appModeOff: "由 Jev 判断要不要做成应用",
    sendHint: "↵ 发送 · ⇧↵ 换行", willQueue: "正忙——会排队",
    queuedN: (n) => `${n} 条排队中`, waiting: "排队中", stopped: "已中断。",
    needPrompt: "没有内容。", needKey: "先添加密钥。",
    needWorkspace: "开始任务前先选好工作区。",

    panelWs: "工作区", panelKeys: "密钥", panelModels: "模型", panelJev: "Jev",
    none: "无", fromEnv: ".env", ready: "就绪", missing: "缺少",
    nKeys: (n) => `${n} 个密钥`, nModels: (n) => `${n} 个模型`,

    you: "你", jevia: "JEVia", jevOnly: "只用 Jev", via: "经",
    copy: "复制", copied: "已复制", again: "改一下再发", savedTo: "已保存到",
    details: "账目", openApp: "打开应用", outputs: "产出", download: "下载",
    cache: "缓存命中", wall: "耗时", unsure: "存疑",
    gistYes: "是", gistNo: "否", gistIs: "判读", gistUnsure: "拿不准",
    gistCount: (n, u) => `${n} 个判断${u ? `，${u} 个拿不准` : ""} · 一次 Jev 调用`,
    judged: "Jev 的判断", showAll: "逐条看完整判断",
    composed: "由 Jev 组装", layout: "布局", layouts: { single: "单栏", split: "主栏 + 侧栏", grid: "网格" },
    components: {
      hero: "标题", stats: "数字", form: "表单", table: "表格", cards: "卡片", chart: "图表",
      filter: "搜索", checklist: "清单", timeline: "时间线", tabs: "标签页", steps: "进度",
      text: "文字", list: "列表", callout: "提示",
    },
    sources: "来源", web: "联网",
    stSearch: "搜索", stPicked: "筛选", stFetch: "读取", stFilter: "留下",
    picked: (a, b) => `${b} 条里选 ${a} 条`, keptOf: (a, b, e) => `${b} 段里留 ${a} 段 · 充分度 ${e}`,
    strategies: {
      declared: "指定", one_choice: "分类", one_score: "打分", one_noul: "是非",
      generation_only: "写作", llm_only: "直连", app: "应用",
    },
    ops: { yes: "是", no: "否", is: "=", at_least: "≥", below: "<" },
    skips: { decisions_only: "只出判断", jev_only: "只出判断", gate: "被拦下" },
    steps_: {
      assess: (d) => (d.app ? "做成应用" : d.needs_research ? "需要联网" : "材料够用")
        + (d.multi_step ? " · 多阶段" : "")
        + (d.skill ? ` · ${d.skill}` : ""),
      plan_free: () => "本地识别出计划",
      plan_compiled: (d) => `拆出 ${d.decisions} 个判断，计划已缓存`,
      research: (d) => `${d.hits} 条结果 → 留 ${d.kept}/${d.sections} 段，${d.sources} 个来源`,
      route: (d) => `${d.steps} 个步骤，用了 ${d.models} 个模型${d.skipped ? `，跳过 ${d.skipped} 个` : ""}`,
      jev_batch: (d) => `${d.decisions} 个判断一次问完${d.sized_model ? "，并定档" : ""}${d.uncertain ? `，${d.uncertain} 个存疑` : ""}`,
      gate: (d) => `跳过 — ${d.condition_text || d.condition}`,
      gate_ignored: () => "已查到资料，忽略闸门",
      jev_only: () => "无需生成",
      model: (d) => `${d.model}${d.rounded_up ? "（升档）" : ""}`,
      model_pinned: (d) => `${d.model}，指定`, model_forced: (d) => `${d.model}`,
      generate: (d) => `${d.model} · ${d.output_tokens} tokens`,
      subtask: (d) => `${d.title} — ${d.model}`,
      tool_gate: (d) => `${d.asked || 0} 次工具调用放行 ${d.allowed || 0} 次`,
      assemble: (d) => `用 ${d.model} 合成一篇`,
      assemble_free: (d) => `${d.sections} 段直接拼接`,
      escalate: (d) => `${d.count} 个交给 ${d.model}`,
      guard: () => "已检查输出", retry: () => "没答到点上——重做一次",
      compose: (d) => (d.kind === "code" ? "需要自写代码" : `${(d.components || []).length} 个组件，${d.layout}`),
      layout: (d) => `${(d.side || []).length} 个放进侧栏`,
      app_fill: (d) => `文字由 ${d.model} 填写`,
      failover: (d) => `${d.from} 不可用（${d.reason}）→ 改用 ${d.to}`,
      app_write: (d) => `由 ${d.model} 编写 · ${Math.max(1, Math.round((d.chars || 0) / 1024))} KB`,
    },

    wsTitle: "选择工作区", wsNote: "所有任务、文件和应用都保存在这个文件夹里。",
    use: "用这个文件夹", newHere: "在这里新建", newHereName: "名字",
    create: "创建", cancel: "取消", typePath: "直接输入路径…", close: "关闭", enter: "进入",
    wsEmpty: "这里没有子文件夹。", wsMissing: "这个文件夹还不存在。",
    wsReady: (n) => `可用 · 里面有 ${n} 个文件夹`, wsReadonly: "这个文件夹不可写。",
    created: (n) => `已创建「${n}」。`, wsSet: "工作区已设为",

    welcome: "设置 JEVia", welcomeKey: "粘贴一个 OpenRouter 密钥就能开始。Jev 和模型都靠它；其他服务商之后可以再加。",
    welcomeGet: "申请密钥", otherVendors: "用其他服务商", start: "继续", later: "稍后",

    prefs: "设置", saved: "已保存",
    tabTools: "工具", toolsNote: "一次运行可以做什么，以及可以用哪些工具。",
    tabKeys: "密钥", tabModels: "模型", tabSkills: "技能", tabLoops: "循环", tabMemory: "记忆", tabBehaviour: "行为",
    keysNote: "用哪家就加哪家的密钥。密钥只存在这个浏览器里，只发给对应的服务商。",
    jevNeedsKey: "Jev 通过 OpenRouter 或 TypeSafe 调用。至少加一个，JEVia 才能做判断。",
    addKey: "添加密钥", keyPlaceholder: "粘贴密钥", baseUrl: "接口地址", label: "名称",
    getKey: "申请密钥", addAndTest: "添加并测试", testing: "测试中…", remove: "移除",
    keyOk: (n) => `已连接 · ${n} 个模型`, keyAdded: "密钥已添加", keyRemoved: "密钥已移除",
    jevHere: "Jev", chatHere: "模型", envKey: "来自 .env", noKeys: "还没有密钥。",
    modelsNote: "每个任务都用够用的最便宜的模型。不同强度各加几个。",
    yourModels: "在用", addModels: "添加模型", browseWith: "浏览",
    search: "搜索", tabAll: "全部", tabFree: "免费", tabCheap: "1 美元以下", tabAdded: "已添加",
    add: "添加", added: "已加", free: "免费", noPrice: "无价格",
    noModels: "还没有模型——至少加一个。", needChatKey: "先添加一个能调用模型的密钥。",
    loading: "加载中…", tierWhy: ["", "抄写和改格式", "日常写作", "推理和代码", "最难的活"],
    modelAdded: "模型已添加", modelRemoved: "模型已移除",
    skillsNote: "技能是一套做事的规矩。JEVia 每个任务会自己挑一个，也可以在输入框里指定。",
    newSkill: "新建技能", install: "安装", installFrom: "从链接安装（GitHub 或 .md 原文）",
    builtIn: "内置", yours: "工作区", edit: "编辑", back: "返回", save: "保存",
    skillSaved: "技能已保存", skillDeleted: "技能已移除", skillInstalled: "技能已安装",
    skillsNeedWs: "新建或修改的技能存在工作区里——先选一个工作区。",
    loopsNote: "定时任务按时间运行。给它一个目标就成了循环：一直做，直到 Jev 判断目标达成。",
    loopName: "名称", loopPrompt: "要做什么？", loopEvery: "每隔", loopGoal: "直到（可选目标）",
    loopGoalHint: "比如：稿子少于 200 字，而且有明确的行动号召",
    loopMax: "最多", rounds: "轮", startNow: "立即开始", createLoop: "创建",
    loopKeyWarn: "密钥会存在工作区里（只有你能读），这样关掉浏览器也能运行。",
    noLoops: "还没有定时任务。", loopsNeedWs: "先选工作区——定时任务需要存在某个地方。",
    runNow: "立即运行", pause: "暂停", resume: "继续", lastRun: "上次", never: "从未",
    status: { active: "运行中", paused: "已暂停", done: "已完成", failed: "失败" },
    goalMet: "目标达成", runLimit: "到达轮数上限", loopTag: "循环", goal: "目标", loopCreated: "已创建", minutes: "分钟", hours: "小时", day: "天",
    everyN: (m) => (m % 1440 === 0 ? `每 ${m / 1440} 天` : m % 60 === 0 ? `每 ${m / 60} 小时` : `每 ${m} 分钟`),
    memoryNote: "JEVia 了解到的关于你的事。用来让回答更贴合你，随时可以删除。",
    memoryOn: "记住我说过的关于我自己的事", rememberThis: "添加一条要记住的事",
    forget: "忘掉", forgetAll: "全部忘掉", noFacts: "还没有记住任何事。", memoryNeedsWs: "记忆存在工作区里——先选一个工作区。",
    stated: "你说过", typed: "你添加的",
    behaviourNote: "JEVia 该多谨慎、多省钱。",
    stance: [
      { id: "thrifty", t: "省", d: "少调模型" },
      { id: "balanced", t: "均衡", d: "默认" },
      { id: "careful", t: "稳", d: "拿不准就复核" },
    ],
    optResearch: "联网检索", optResearchD: "任务需要事实时，先搜索并阅读网页。",
    optEscalate: "复核拿不准的判断", optEscalateD: "Jev 拿不准时，交给模型再看一遍。",
    optGuard: "检查每个回答", optGuardD: "Jev 对照任务检查回答；没答到点上就重做一次。",
    optApps: "做应用", optApps_D: "你要工具、表单或看板时，Jev 会组装一个能用的。",
    optTools: "工作区工具", optToolsD: "允许子任务读写工作区里的文件。",
    expand: "展开全文", collapse: "收起", latest: "回到最新",
    thinking: "Jev 正在判断任务…", planning: (x) => `Jev：${x} —— 正在规划步骤…`, researching: "正在搜索和阅读…",
    jevLevel: (n) => `Jev 判定难度 ${n}/4`, rejected: (x) => `更便宜的 ${x} 不够格`,
    switched: (a, b) => `${a} 不可用，改用 ${b}`,
    workers: "子代理", worker: "子代理", bespoke: "定制", doc: "文档", brief: "工作说明",
    status_: { pending: "等待", running: "工作中", done: "完成", skipped: "跳过", failed: "失败" },
    revisedN: (n) => `改过 ${n} 次`, revisedNote: "已重写它负责的部分。",
    talkTo: "告诉这个子代理要改什么——它会重写自己负责的部分", answerNotSynced: "总答案是整体重写过的，所以里面还是这部分的旧版本。",
    assembled: "组装完成", filling: (m) => `模块就位 · 文字由 ${m} 填写`,
    log: {
      tool: (e) => `${e.ok ? "调用" : "拒绝"} ${e.name}`,
      search: (e) => `搜索「${e.q}」`, read: (e) => `打开 ${e.n} 个网页`,
      kept: (e) => `留下 ${e.n} 段资料`, write: (e) => `用 ${e.model} 写作`,
      error: (e) => e.message || "失败",
      failover: (e) => `${e.from} 不可用（${e.reason}），改用 ${e.to}`,
    },
    slashTitle: "技能与命令", slashHint: "↑↓ 选择 · ↵ 使用 · esc 关闭", slashEmpty: "没有匹配的",
    skillLabel: "技能", skillAutoShort: "自动", cmdApp: "做成应用", cmdAppOff: "由 Jev 判断要不要做成应用",
    cmdNone: "不用技能", cmdAuto: "让 Jev 挑技能",
    skillNames: {
      "research-brief": "研究简报", "code-review": "代码审查", "support-reply": "客服回复",
      summarise: "摘要", "compare-options": "方案对比", "data-extraction": "信息提取",
      "writing-clear": "清晰写作", translate: "翻译",
    },
    skillDescs: {
      "research-brief": "查资料并写成一份有出处的简报。",
      "code-review": "审查代码改动、合并请求或修改方案。",
      "support-reply": "回复客户、用户或公众的来信。",
      summarise: "把长材料压缩成能直接拿来用的要点。",
      "compare-options": "比较几个方案并给出推荐。",
      "data-extraction": "从材料里按固定格式提取信息。",
      "writing-clear": "写出忙碌的读者也会读完的文字。",
      translate: "在语言之间翻译，保留真正重要的东西。",
    },
    forging: (kb, model) => `正在编写应用 · ${kb} KB${model ? " · " + model : ""}`,
    kindCode: "自写代码", forgeNote: "标准组件做不了这个——由模型完整写出来。",
    run: "运行", webSources: "网页来源", openSite: "打开", sectionsKept: (n) => `用到 ${n} 段`,
    canvasEmpty: "应用、文档和任务读过的网页会出现在这里。",
    heroDisplay: "Judge. Write. Build.",
    advanced: "专业调整", thAbstain: "存疑阈值", thLow: "是非下界", thHigh: "是非上界", jevModel: "Jev 模型",
    interrupted: "已中断：页面在完成前被关闭，之后没有再发起新的步骤。",
    uploadSkill: "上传",
    plainHttpKey: "这个地址是明文 http：密钥会以未加密的方式经过网络。",
    skillsAdded: (n, ignored) => `已添加 ${n} 个技能${ignored ? `，忽略 ${ignored} 个文件` : ""}`,
    stoppedListening: "已停止接收。服务器上的任务可能仍会完成，最后一次请求仍可能计费。",
    dp: {
      qualityTitle: "花钱方式",
      qualityNote: "Jev 对每一步的判断不变；这里决定从这个档位的哪一侧取模型。",
      qualities: { thrift: "够用就好", best: "用最强的" },
      qualityNotes: {
        thrift: "每步用刚好达标的最便宜模型，这是默认的算法。",
        best: "凡是需要写东西的步骤，都用你配置里最强的模型。",
      },
      mcpTitle: "外部工具（MCP）",
      mcpNote: "MCP 服务器是一个提供工具的程序，会以你的身份在本机运行，所以只能在这里配置，模型无法添加。",
      mcpName: "名称", mcpCommand: "命令", mcpAdd: "添加服务器",
      mcpWarning: "只添加你信任的服务器：命令会以你的身份执行。",
      mcpReady: (n) => `${n} 个工具`, mcpFailed: "启动失败",
      mcpOff: "已关闭", mcpEnable: "启用", mcpDisable: "停用",
      mcpEmpty: "还没有 MCP 服务器。",
      toolsTitle: "工具权限", toolsNote: "一次运行可以在你机器上做什么。任何改动都会先经过判断，且只在工作区内。",
      toolSets: { read: "只读", write: "读写文件", full: "还能执行命令" },
      toolSetNotes: {
        read: "读文件、搜索、抓网页，不改动任何东西。",
        write: "还可以在工作区内写入和修改文件。",
        full: "还可以执行 shell 命令和代码，需要设置 JEVIA_ENABLE_SHELL=1。",
      },
      planModePref: "先给计划",
      planModeNote: "动手之前先说要做什么并等你确认。你说要改哪里，它会重新规划。",
      approvePref: "每次改动都问我",
      approveNote: "在安全判断之外，每次写入、修改或执行都等你点头。",
      loopPref: "允许模型分步调用工具",
      loopNote: "它可以看完结果再决定下一步。关闭后每次回答都是一次性请求。",
      maxSteps: "每回合步数", maxStepsNote: "一次回答最多可以查看几次再落笔。",
      ofOpen: (n) => `共 ${n} 个待回答`,
      questionAsked: "任务有个问题要问你", approvalNeeded: "这个改动要不要执行？",
      approvalNote: "它会改变这次对话之外的东西。",
      planReady: "开始动手前的计划", planChange: "说说该怎么改…",
      answerHere: "你的回答…", send: "发送",
      planTitle: "计划", planWaiting: "等你确认", planApproved: "你已确认", planChanged: "按你的反馈改过",
      stepsTitle: "步骤与工具",
      stepsLine: (n, t) => `${n} 步 · ${t} 次工具调用`,
      stepN: (n) => `第 ${n} 步`,
      calledTools: (n) => `调用了 ${n} 个工具`,
      waitingModel: "等待模型…", answered: "已回答",
      toolsFailed: (n) => `${n} 次被拒或失败`,
      compacted: (n) => `上下文压缩 ×${n}`,
      compactedLine: (a, b, n) => `较早的对话已压缩：${a} → ${b} tokens，替换了 ${n} 条消息`,
      toolStates: { running: "运行中…", ok: "成功", failed: "失败", refused: "已拒绝" },
      refusals: {
        unknown_tool: "本次运行没有这个工具", malformed_arguments: "参数不是合法 JSON",
        gate_refused: "被安全判断拒绝", user_refused: "你拒绝了",
        gate_not_asked: "不在你要求的范围内", gate_unsafe: "判定为不安全",
        gate_unavailable: "无法连到安全判断",
        already_refused: "同一个调用，已经拒过",
        no_gate: "无法核查", no_tools: "本次运行关闭了工具",
      },
      showEarlier: (n) => `显示更早的 ${n} 个批次`,
      showAllQuestions: (n) => `显示全部 ${n} 个问题`,
      qnames: {
        __needs_research__: "是否需要联网", __multi_step__: "是否分多步", __wants_app__: "是否要做应用",
        __skill__: "用哪个技能", __enough__: "证据是否充分", __capability__: "所需能力档位",
        __independent__: "步骤能否并行", __assembly__: "是否重写成整体",
        on_task: "回答是否切题", refused: "回答是否拒绝", web: "是否需要新资料",
      },
      actions: {
        "search the web": "联网搜索",
        "use the material given": "使用已给材料",
        "compile a plan with steps": "编写分步计划",
        "no forced split": "不强制拆分",
        "build an app": "构建应用",
        "answer in text": "文字回答",
        "no skill": "不用技能",
        "skip generation": "跳过生成",
        "generate anyway": "照常生成",
        "no generation call": "不调用生成",
        "run": "运行",
        "block": "拦截",
        "keep the partial text; no automatic retry": "保留已输出部分，不自动重试",
      },
      viewDecisions: "查看判断", decisionSummary: "判断摘要", decisions: "判断",
      countsLine: (q, j, l) => `${q} 项判断 · ${j} 次 Jev 调用 · ${l} 次语言模型调用`,
      oneCall: (n) => `1 次调用 · ${n} 个问题`,
      stages: {
        running: "运行中", assessing: "评估任务", planning: "规划", searching: "联网搜索",
        reading: "读取来源", choosingSources: "挑选来源", classifying: "筛选材料",
        checkingEvidence: "检查证据", routing: "分配步骤", judging: "判断",
        writing: "写作", assembling: "组装", checkingAnswer: "检查回答",
        reviewing: "复核存疑判断", runningTools: "运行工具", buildingApp: "构建应用",
        revising: "修订",
      },
      status: {
        running: "运行中", completed: "已完成", needs_review: "待复核", cancelled: "已取消",
        cancel_requested: "已请求取消", failed: "失败", partial: "部分结果",
        interrupted: "已中断",
      },
      actors: { jev: "Jev", policy: "策略", llm: "语言模型", tool: "工具" },
      purposes: {
        assess: "评估任务", triage: "挑选来源", filter: "筛选材料",
        sufficiency: "检查证据", route: "分配步骤", decide: "判断", compose: "组合应用",
        layout: "应用布局", guard: "检查回答", gate: "检查工具动作",
        revise_assess: "评估修订", loop: "检查目标",
      },
      reasons: {
        no_qualified_model: "无合格模型", jev_failed: "Jev 请求失败",
        low_confidence: "置信度低", evidence_unknown: "证据情况未知",
        component_schema: "组件校验失败",
      },
      sources_: { live: "实时", recorded: "记录回放", demo: "演示回放" },
      types: { noul: "是否题", choice: "选择题", score: "评分题" },
      groups: { kept: "保留", review: "待复核", excluded: "排除", not_assessed: "未判断" },
      sufficiency: {
        sufficient: "充分", insufficient: "不充分", unknown: "未知",
        not_rechecked: "此步骤未重新检查", not_checked: "未检查",
      },
      stops: {
        sufficient: "停止：证据充分", budget_exhausted: "停止：搜索轮数用完",
        no_new_sources: "停止：没有新来源", error: "停止：出错", cancelled: "停止：已取消",
      },
      costSources: { provider_reported: "服务商报告", price_table_estimated: "价表估算", unknown: "未知" },
      modes: { written: "已写", partial: "部分", joined: "拼接", rewritten: "重写", revised: "已修订", stale: "待同步" },
      tech: {
        question: "问题 ID", batch: "批次", attempt: "尝试", call: "调用", costSource: "费用来源",
        cost: "费用", operation: "操作", stage: "阶段", evidenceSet: "证据集", limit: "预算（字符）",
      },
      rules: {
        "assess.research_at_or_above": (i, a) => `联网：P(yes) ${fmt(i.probability_yes)}，阈值 ${fmt(i.threshold)} → ${a}`,
        "assess.multi_step_at_or_above": (i, a) => `多步骤：P(yes) ${fmt(i.probability_yes)}，阈值 ${fmt(i.threshold)} → ${a}`,
        "assess.app_at_or_above": (i, a) => `应用：P(yes) ${fmt(i.probability_yes)}，阈值 ${fmt(i.threshold)} → ${a}`,
        "assess.skill_confidence_at_or_above": (i, a) => `技能：置信度 ${fmt(i.confidence)}，阈值 ${fmt(i.threshold)} → ${a}`,
        "triage.keep_above": (i, a) => `打开 P(yes) ≥ ${fmt(i.threshold)} 的结果，最多 ${i.top_k} 个 → ${a}`,
        "triage.keep_best_when_none_pass": (i, a) => `没有结果达到 ${fmt(i.threshold)}，打开最好的一个 → ${a}`,
        "triage.fallback_rank_order": (i, a) => `Jev 未回答，按搜索引擎顺序 → ${a}`,
        "capability.round_to_nearest": (i) => `原始评分 ${fmt(i.raw)} 取最近档位${i.adopted != null ? `（${i.adopted}）` : ""}`,
        "capability.round_up_below_certainty": () => "置信度低于上调阈值，提高一档",
        "capability.round_up_relaxed": () => "上调后的档位没有可用模型，改用 Jev 给出的档位",
        "capability.no_answer_cheapest": () => "没有能力评分，使用最便宜的模型",
        "role.min_capability": () => "提高到该角色的最低档位",
        "capability.level0_no_generation": () => "0 档：判断即答案，不调用生成",
        "capability.level0_without_decisions_generates": () => "0 档但没有可用判断：用最便宜的模型生成",
        "gate.skip_generation_when": (i, a) => `计划中的跳过条件成立 → ${a}`,
        "gate.ignored_when_research_found_evidence": (i, a) => `研究找到了证据，忽略跳过条件 → ${a}`,
        "failover.before_output": (i, a) => `${i.from} 在输出前失败（${i.reason}）→ ${a}`,
        "failover.not_after_output": (i, a) => `输出 ${i.streamed_chars} 字符后失败 → ${a}`,
        "review.escalate_low_confidence": (i, a) => `置信度低 → ${a}`,
        "guard.retry_once_when_off_task": (i, a) => `检查发现回答偏题 → ${a}`,
        "tools.gate_allow_at_or_above": (i, a) => `${i.tool}：P(yes) ${fmt(i.probability_yes)}，阈值 ${fmt(i.threshold)} → ${a}`,
        "routing.jev_failed_cheapest": () => "分配未得到回答，使用最便宜的模型",
        "r01.contradiction_raises_level": () => "材料互相矛盾：提高一档（试验）",
        "r01.incomplete_evidence_fetches_more": () => "材料不完整：此步骤先补资料（试验）",
        "plan.pinned_model": () => "计划指定了模型",
      },
      sum: { assess: "评估任务", evidence: "筛选材料", routing: "分配步骤", decisions: "判断" },
      selectedN: (n) => `${n} 个由策略选定`,
      groupsCount: (c) => `保留 ${c.kept || 0} · 待复核 ${c.review || 0} · 排除 ${c.excluded || 0} · 未判断 ${c.not_assessed || 0}`,
      discoveredLine: (c) => `发现 ${c.discovered || 0} · 提交 ${c.submitted || 0} · 有效判断 ${c.validly_evaluated || 0}`,
      round: (n) => `第 ${n} 轮`, moreItems: (n) => `另有 ${n} 条未列出`,
      visibleRange: (v) => `判断了 ${v[2]} 字符中的 ${v[1]}`,
      checkedDelivered: (n, c) => `检查了写作将收到的 ${n} 段（${c} 字符）`,
      deliveryCheck: "此步骤只收到已检查证据的一部分",
      excludedNote: "排除表示没有交给写作模型，并未删除任何内容。",
      material: "材料", stepMaterial: "某个步骤的材料",
      routingTitle: "分配", assessedByJev: "Jev 评估", selectedByPolicy: "策略选定",
      noQualified: "无合格模型", belowLevel: "低于所需档位", requiredLevel: "所需档位",
      rawScore: "原始评分", adopted: "采用", onScale: (a, b) => `量表 ${a}–${b}`, role: "角色", fromPlan: "来自计划",
      candidates: "候选模型", byCost: "合格", priceUnknown: "价格未知", freeAtRate: "按配置价格免费",
      costBasis: "按配置成本排序（输入价 + 3× 输出价），不代表完成任务的最低总价。",
      bestAvailable: (n) => `可用最高：${n} 档`, downgraded: "经允许降级",
      routeWhy: (need, n) => `所需档位 ${need}；合格候选 ${n} 个；按配置成本排序`,
      addModel: "添加模型", allowDowngrade: "允许降级",
      generationTitle: "生成", generationSkipped: "跳过生成", zeroLLM: "0 次语言模型调用",
      noGenCallStep: "此步骤没有生成调用", scopeRun: "整个回答", scopeStep: (t) => `步骤：${t}`,
      needsReview: "待复核", laterAttempt: (a) => `之后，${a}`,
      costsTitle: "调用与费用", judgements: "判断数", jevCalls: "Jev 调用", llmCalls: "语言模型调用",
      knownCost: "已知费用", unknownCost: "费用未知（请求数）",
      outputsTitle: "产出版本", wholeAnswer: "整个回答", dependsOn: "依据", needsSync: "待同步",
      needsSyncNote: "整体重写之后，某个部分又改了。", syncNow: "立即同步", synced: "已同步",
      componentsTitle: "应用组件", componentSlots: "组件槽位", componentReady: "已渲染",
      componentFailed: "组件校验失败", exampleData: "示例数据", codeKind: "写成独立代码",
      pYes: "P(yes)", pYesShort: "P(yes)", pOf: "p", confidence: "置信度", threshold: "阈值",
      distribution: "分布", total: "合计", viewAll: "查看全部", unassigned: "未归类",
      groupView: "按类别分组", listView: "列表", unavailable: "不可用", missing: "缺少答案",
      failed: "失败", settled: "已返回", waitingJev: "等待 Jev…",
      whyThis: "为什么采用这个结果", technical: "技术细节",
      cancelRequested: "已请求取消", mayBill: "最后一次请求仍可能计费",
      traceUnavailable: "没有详细记录", recordGap: (g) => `记录缺口：缺少事件 ${g.map(([a, b]) => (a === b ? a : `${a}–${b}`)).join("、")}`,
      loadFull: "加载完整记录", exportRecord: "导出记录",
      demoNote: "由测试样例生成，没有调用任何模型，数值不是实测结果。",
      demoTitle: "演示回放", demoPick: "选择一个场景", replay: "重放", speed: "速度",
      motion: "动效", motionNote: "只决定状态变化如何呈现；任何设置下结果和调用次数都相同。",
      motionModes: { system: "跟随系统", reduced: "减少", off: "关闭" },
      downgradePref: "允许有标识的降级",
      downgradeNote: "没有模型达到某步骤档位时，用最强的模型运行并标注。关闭时该步骤等待复核。",
      extraRouting: "额外分配维度（试验）",
      extraRoutingNote: "同时判断材料是否完整、是否矛盾。在证明有效之前默认关闭。",
      loopIteration: (n, m) => `第 ${n} 轮${m ? ` / 共 ${m}` : ""}`, goalMet: "达成目标", limitReached: "达到上限",
      checkedByCode: "代码检查", checkedByJev: "Jev 检查",
    },
  },
};
